version: "3.9"  

services:
    srvbridge: 
        #image: containous/whoami
        image: nginx
        hostname: srvbridge
        domainname: srvbridge
        container_name: srvbridge
#        user: "root"
#        cap_add:
#            - NET_ADMIN        
#        ports:
#          - "8081:80"
        networks:
            net:
                ipv4_address: 192.168.1.3          

networks:
  net:
    driver: macvlan
    driver_opts:
      parent: ens33
    ipam:
      config:
        - subnet: "192.168.1.1/24"
          #ip_range: "192.168.1.0/24"
          #gateway: "192.168.1.1"


  
